favicon: https://img.imql.life/nav.svg
banner: /images/webstack_banner_cn.png

logo:
  expanded: /images/webstack_icon_producthunt.png
  collapsed: /images/collapsed.png
  dark: /images/dark.png

flag:
  icon: flag-cn
  name: Chinese

search: true

githubCorner: '<a href="https://github.dev/ql-isaac/nav" class="github-corner" aria-label="View and edit source on GitHub"><svg width="80" height="80" viewBox="0 0 250 250" style="fill:#151513; color:#fff; position: absolute; top: 0; border: 0; right: 0;" aria-hidden="true"><path d="M0,0 L115,115 L130,115 L142,142 L250,250 L250,0 Z"></path><path d="M128.3,109.0 C113.8,99.7 119.0,89.6 119.0,89.6 C122.0,82.7 120.5,78.6 120.5,78.6 C119.2,72.0 123.4,76.3 123.4,76.3 C127.3,80.9 125.5,87.3 125.5,87.3 C122.9,97.6 130.6,101.9 134.4,103.2" fill="currentColor" style="transform-origin: 130px 106px;" class="octo-arm"></path><path d="M115.0,115.0 C114.9,115.1 118.7,116.5 119.8,115.4 L133.7,101.6 C136.9,99.2 139.9,98.4 142.2,98.6 C133.8,88.0 127.5,74.4 143.8,58.0 C148.5,53.4 154.0,51.2 159.7,51.0 C160.3,49.4 163.2,43.6 171.4,40.1 C171.4,40.1 176.1,42.5 178.8,56.2 C183.1,58.6 187.2,61.8 190.9,65.4 C194.5,69.0 197.7,73.2 200.1,77.6 C213.8,80.2 216.3,84.9 216.3,84.9 C212.7,93.1 206.9,96.0 205.4,96.6 C205.1,102.4 203.0,107.8 198.3,112.5 C181.9,128.9 168.3,122.5 157.7,114.1 C157.9,116.9 156.7,120.9 152.7,124.9 L141.0,136.5 C139.8,137.7 141.6,141.9 141.8,141.8 Z" fill="currentColor" class="octo-body"></path></svg></a><style>.github-corner:hover .octo-arm{animation:octocat-wave 560ms ease-in-out}@keyframes octocat-wave{0%,100%{transform:rotate(0)}20%,60%{transform:rotate(-25deg)}40%,80%{transform:rotate(10deg)}}@media (max-width:500px){.github-corner:hover .octo-arm{animation:none}.github-corner .octo-arm{animation:octocat-wave 560ms ease-in-out}}</style>'

menu:
  - name: 个人站点
    icon: fas fa-user-alt fa-fw
    config: 个人站点
  - name: 知识管理
    icon: fas fa-lightbulb fa-fw
    config: 知识管理
  - name: 云服务
    icon: fas fa-cloud fa-fw
    config: 云服务
  - name: 工具
    icon: fas fa-tools fa-fw
    config: 工具    
  - name: 开源项目
    icon: fab fa-github fa-fw
    config: 开源项目
  - name: 优质软件
    icon: fas fa-code fa-fw
    config: 优质软件
  - name: 优质自媒体
    icon: fab fa-creative-commons fa-fw
    config: 优质自媒体
  - name: 参考资料
    icon: far fa-folder fa-fw
    config: 参考资料
  - name: 电子游戏
    icon: fas fa-gamepad fa-fw
    config: 电子游戏
  - name: 资源下载
    icon: fas fa-download
    config: 资源下载
  - name: 设计
    icon: fab fa-sketch fa-fw
    submenu:
      - name: 图片设计
        icon: fas fa-image fa-fw
        config: 图片设计
      - name: 网页设计
        icon: fas fa-magic fa-fw
        config: 网页设计
  - name: 素材资源
    icon: fas fa-meteor fa-fw
    submenu:
      - name: 图标
        icon: fas fa-icons fa-fw
        config: 图标
      - name: 图片
        icon: fas fa-images fa-fw
        config: 图片
      - name: 配色
        icon: fas fa-palette fa-fw
        config: 配色
      - name: 字体
        icon: fas fa-font fa-fw
        config: 字体

个人站点:
  - name: ql
    img: https://img.imql.life/www.svg
    url: https://www.imql.life/
    description: 个人首页
  - name: ql's blog
    img: https://img.imql.life/blog.svg
    url: https://blog.imql.life/
    description: 个人博客
  - name: ql's space
    img: https://img.imql.life/space.svg
    url: https://space.imql.life/
    description: 个人空间
  - name: ql's nav
    img: https://img.imql.life/nav.svg
    url: /
    description: 个人导航

知识管理:
  - name: GitHub
    url: https://github.com/
    img: https://img.imql.life/logos/GitHub.svg
    description: 交友平台
  - name: Gitee
    url: https://gitee.com/ql-isaac
    img: https://img.imql.life/logos/Gitee.svg
    description: 和 GitHub 相比唯一的优点：访问快？
  - name: CODING
    img: https://img.imql.life/logos/CODING.svg
    url: https://ql-isaac.coding.net/user
    description: 一站式软件研发管理协作平台
  - name: Notion
    img: https://img.imql.life/logos/Notion.svg
    url: https://www.notion.so/
    description: All-in-one workspace
  - name: 语雀
    img: https://img.imql.life/logos/语雀.svg
    url: https://www.yuque.com/
    description: 
  - name: 幕布（微信登陆）
    img: https://img.imql.life/logos/mubu.svg
    url: https://mubu.com/app
    description: 不只是大纲笔记，更是一种思考方式。
  - name: ProcessOn（微信登陆）
    img: https://img.imql.life/logos/ProcessOn.svg
    url: https://www.processon.com/diagrams
    description: 免费在线流程图思维导图

云服务:
  - name: QQ 邮箱
    img: https://img.imql.life/logos/QQ邮箱.svg
    url: https://mail.qq.com/
    description:
  - name: 谷歌邮箱
    img: https://img.imql.life/logos/Gmail.svg
    url: https://mail.google.com/
    description:
  - name: 头像（Gravatar）
    img: https://img.imql.life/logos/Gravatar.svg
    url: https://cn.gravatar.com/emails
    description: 绑定邮箱的全球通用头像。
  - name: DaoVoice
    img: https://img.imql.life/logos/DaoVoice.svg
    url: http://dashboard.daovoice.io/app/006213f1/settings/general
    description: 网页在线通讯
  - name: 腾讯云
    img: https://img.imql.life/logos/腾讯云.svg
    url: https://console.cloud.tencent.com/
    description: CDN/COS/Webify/CloudBase/DNSpod
  - name: Vercel
    img: https://img.imql.life/logos/Vercel.svg
    url: https://vercel.com/dashboard
    description: 不仅仅是静态网站托管。
  - name: LeanCloud
    img: https://img.imql.life/logos/LeanCloud.svg
    url: https://console.leancloud.cn/apps
    description: 
  - name: 阿里云
    img: https://img.imql.life/logos/阿里云.svg
    url: https://www.aliyun.com/
    description:

工具:
  - name: 友盟+
    img: https://img.imql.life/logos/友盟+.svg
    url: https://www.umeng.com/
    description: U-Web - 网站流量统计分析工具
  - name: 网站测速（站长工具）
    img: https://img.imql.life/logos/站长之家.svg
    url: https://tool.chinaz.com/speedtest/
    description:
  - name: MySSL
    img: https://img.imql.life/logos/MySSL.svg
    url: https://myssl.com/
    description: 网站监测

开源项目:
  - name: Hexo
    img: https://img.imql.life/logos/GitHub.svg
    url: https://github.com/hexojs/hexo
    description: A fast, simple & powerful blog framework, powered by Node.js.
  - name: Twikoo
    img: https://img.imql.life/logos/GitHub.svg
    url: https://github.com/imaegoo/twikoo
    description: 一个简洁、安全、免费的静态网站评论系统。
  - name: Butterfly
    img: https://img.imql.life/logos/GitHub.svg
    url: https://github.com/jerryc127/hexo-theme-butterfly
    description: 我的主站使用的主题
  - name: Ventoy
    img: https://img.imql.life/logos/GitHub.svg
    url: https://github.com/ventoy/Ventoy
    description: A new bootable USB solution.
  - name: Typecho
    img: https://img.imql.life/logos/GitHub.svg
    url: https://github.com/typecho/typecho
    description: A PHP Blogging Platform. Simple and Powerful.
  - name: WebStack
    img: https://img.imql.life/logos/GitHub.svg
    url: https://github.com/HCLonely/hexo-theme-webstack
    description: 我的导航站使用的主题
  - name: Tabby
    img: https://img.imql.life/logos/GitHub.svg
    url: https://github.com/Eugeny/tabby
    description: A terminal for a more modern age
  - name: Notepad3
    img: https://img.imql.life/logos/GitHub.svg
    url: https://github.com/rizonesoft/Notepad3
    description: Windows 自带记事本的升级版
  - name: Windows-Auto-Night-Mode
    img: https://img.imql.life/logos/GitHub.svg
    url: https://github.com/AutoDarkMode/Windows-Auto-Night-Mode
    description: Automatically switches between the dark and light theme of Windows 10 and Windows 11
  - name: frp
    img: https://img.imql.life/logos/GitHub.svg
    url: https://github.com/fatedier/frp
    description: A fast reverse proxy to help you expose a local server behind a NAT or firewall to the internet
  - name: Wox
    img: https://img.imql.life/logos/GitHub.svg
    url: https://github.com/Wox-launcher/Wox
    description: Launcher for Windows, an alternative to Alfred and Launchy

优质软件:
  - name: ScreenToGif
    img: https://img.imql.life/logos/优质软件.svg
    url: https://www.screentogif.com/
    description: GIF 录制
  - name: Carnac
    img: https://img.imql.life/logos/优质软件.svg
    url: http://code52.org/carnac/
    description: 按键操作实时显示工具

优质自媒体:
  - name: 汤质看本质
    img: https://img.imql.life/logos/bilibili.svg
    url: https://space.bilibili.com/362588980/
    description: 祝你成为超人！
  - name: 小马视频
    img: https://img.imql.life/logos/bilibili.svg
    url: https://space.bilibili.com/314363980/
    description: 热爱编程！热爱游戏！
  - name: 大象放映室
    img: https://img.imql.life/logos/bilibili.svg
    url: https://space.bilibili.com/49246269/
    description: 故事、知识、人文精神。
  - name: 思维实验室
    img: https://img.imql.life/logos/bilibili.svg
    url: https://space.bilibili.com/14583962/
    description: 如无必要 勿增实体
  - name: Topbook
    img: https://img.imql.life/logos/bilibili.svg
    url: https://space.bilibili.com/29959830/
    description: 让工具回归工具，让你成为你。
  - name: 动画讲编程
    img: https://img.imql.life/logos/bilibili.svg
    url: https://space.bilibili.com/526619673/
    description: 看动画，学编程，轻松愉快效率高！
  - name: 硬件茶谈
    img: https://img.imql.life/logos/bilibili.svg
    url: https://space.bilibili.com/14871346/
    description:

参考资料:
  - name: 菜鸟教程
    img: https://img.imql.life/logos/RUNOOB.svg
    url: https://www.runoob.com/
    description: 菜鸟教程
  - name: GitHub Actions by Example
    img: https://img.imql.life/logos/知识库.svg
    url: https://www.actionsbyexample.com/index.html
    description:
  - name: GitHub Actions by Example
    img: https://img.imql.life/logos/知识库.svg
    url: https://www.actionsbyexample.com/index.html
    description:
  - name: ArchWiki
    img: https://img.imql.life/logos/ArchLinux.svg
    url: https://wiki.archlinux.org/
    description:
  - name: 网道
    img: https://img.imql.life/logos/知识库.svg
    url: https://wangdoc.com/
    description:

电子游戏:
  - name: 游戏免费拿（Epic）
    img: https://img.imql.life/logos/EPIC.svg
    url: https://www.epicgames.com/store/zh-CN/free-games
    description: 每周白嫖，不玩也得拿。

资源下载:
  - name: ITELL YOU（旧版）
    img: https://img.imql.life/logos/下载.svg
    url: https://msdn.itellyou.cn/
    description:
  - name: ITELL YOU（新版）
    img: https://img.imql.life/logos/下载.svg
    url: https://next.itellyou.cn/
    description:

图片设计:
  - name: StorySet
    img: https://img.imql.life/logos/图片.svg
    url: https://storyset.com/
    description:
  - name: 创客贴
    img: https://img.imql.life/logos/图片.svg
    url: https://www.chuangkit.com/
    description: 让设计触手可得。
  - name: 可画
    img: https://img.imql.life/logos/Canva.svg
    url: https://www.canva.cn/
    description:

网页设计:
  - name: 拟物风格生成
    img: https://img.imql.life/logos/网页设计.svg
    url: https://neumorphism.io/
    description: Generate Soft-UI CSS code
  - name: CODEPEN
    img: https://img.imql.life/logos/CODEPEN.svg
    url: https://codepen.io/
    description:

图标:
  - name: iconfont
    img: https://img.imql.life/logos/iconfont.svg
    url: http://www.iconfont.cn/
    description: 阿里巴巴矢量图标库
  - name: Font Awesome5 图标库
    img: https://img.imql.life/logos/Font-Awesome.svg
    url: https://fontawesome.com/icons?d=gallery&g=hands&m=free
    description: 快速查询 Font Awesome5 的图标。
  - name: Notion Icons
    img: https://img.imql.life/logos/notion_vip_logo.svg
    url: https://www.notion.vip/icons/
    description: Notion Icons
  - name: ICONS8
    img: https://img.imql.life/logos/ICONS8.svg
    url: https://icons8.com/
    description: 图标、插图、照片、音乐和设计工具
  - name: IconPark
    img: https://img.imql.life/logos/IconPark.svg
    url: https://iconpark.oceanengine.com/home
    description:

图片:
  - name: wallhaven
    img: https://img.imql.life/logos/图片.svg
    url: https://wallhaven.cc/
    description: The best wallpapers on the Net!
  - name: Pinterest
    img: https://img.imql.life/logos/图片.svg
    url: https://www.pinterest.com/
    description: 瀑布流的形式展现图片内容，无需用户翻页，新的图片不断自动加载在页面底端。
  - name: Unsplash
    img: https://img.imql.life/logos/图片.svg
    url: https://unsplash.com/
    description: Beautiful, free images and photos that you can download and use for any project. Better than any royalty free or stock photos.
  - name: Colorhub
    img: https://img.imql.life/logos/图片.svg
    url: https://www.colorhub.me/
    description: 高清无版权图片（个人和商业用途免费）
  - name: Pexels
    img: https://img.imql.life/logos/图片.svg
    url: https://www.pexels.com/zh-cn/
    description: 免费素材照片，可以在任何地方使用。免费用于商业用途，无需注明归属。
  - name: Pixabay
    img: https://img.imql.life/logos/图片.svg
    url: https://pixabay.com/
    description: Stunning free images & royalty free stock
  - name: WallpaperHub
    img: https://img.imql.life/logos/图片.svg
    url: https://wallpaperhub.app/
    description: Download free wallpapers for your PC, phone and tablet.
  - name: Behance
    img: https://img.imql.life/logos/图片.svg
    url: https://www.behance.net/
    description: Behance 作品精选
  - name: 站酷 (ZCOOL)
    img: https://img.imql.life/logos/图片.svg
    url: https://www.zcool.com.cn/
    description: 站酷 (ZCOOL)，中国设计师互动平台。深耕设计领域十四年，站酷聚集了 1100 万设计师、摄影师、插画师、艺术家、创意人，设计创意群体中具有较高的影响力与号召力。
  - name: Backiee
    img: https://img.imql.life/logos/图片.svg
    url: https://backiee.com/
    description: The ultimate free wallpaper site and app. Available on Web, iPhone, Android, Xbox, and Windows platform as well.
  - name: Desktop Wallps
    img: https://img.imql.life/logos/图片.svg
    url: http://desktop.hdwallps.com/
    description: HD Wallpaper For Desktop Background
  - name: wallpaperaccess
    img: https://img.imql.life/logos/图片.svg
    url: https://wallpaperaccess.com/
    description: Only the best wallpapers. Daily additions of new, awesome, HD wallpapers for desktop and phones.
  - name: 特效背景生成
    img: https://img.imql.life/logos/图片.svg
    url: https://coolbackgrounds.io/
    description: Cool Backgrounds
  - name: 必应壁纸
    img: https://img.imql.life/logos/图片.svg
    url: https://bing.ioliu.cn/
    description:

配色:
  - name: webkul
    img: https://ae01.alicdn.com/kf/Hebaaa27db8974449ad28d818d5660fb15.png
    url: https://webkul.github.io/coolhue/
    description: Get coolest handpicked gradient colors collection palette for your next project, alternatively copy css or download as image too.
  - name: uigradients
    img: https://ae01.alicdn.com/kf/H9231fd2d81e04b2a9e705e7261e5aeb5E.png
    url: https://uigradients.com/
    description: uiGradients is a handpicked collection of beautiful color gradients for designers and developers.
  - name: adobe color
    img: https://ae01.alicdn.com/kf/Hca2e611ffa2e413ba5d892dc2404ad0a4.png
    url: https://color.adobe.com/
    description: Adobe 家的配色

字体:
  - name: Google Fonts
    img: https://img.imql.life/logos/Google-Font.svg
    url: https://fonts.google.com/
    description:

about:
  url: /about/
  icon: far fa-heart
  name: 关于本站

aboutPage:
  website:
    head: 关于本站
    html: <blockquote><p>本站是<a href="https://imql.life/">ql-isaac</a>的个人网址导航。</p></blockquote>
  webmaster:
    head: 关于站长
    name: ql-isaac
    url: https://imql.life/
    img: https://img.imql.life/avatar.jpg
    description: It's beautiful day!
    html: ''

since: 2020

busuanzi:
  enable: true
  position: sidebar # 'footer','sidebar'
  pv: 本站总访问量$pv
  uv: 本站总访客数$uv

custom:
  head: |- # 以下内容插入到<head></head>标签内，可设置多行，注意每行开头至少四个空格
    <!-- 直接添加html内容即可 -->
    <!-- 可设置多行 -->
  body: |- # 以下内容插入到</body>标签之前，可设置多行，注意每行开头至少四个空格
    <!-- 直接添加html内容即可 -->
    <!-- 可设置多行 -->

js:
  header: /js/header.js
  footer: /js/footer.js
  jquery: /js/jquery-1.11.1.min.js
  bootstrap: /js/bootstrap.min.js
  TweenMax: /js/TweenMax.min.js
  resizeable: /js/resizeable.min.js
  joinable: /js/joinable.js
  xenonApi: /js/xenon-api.min.js
  xenonToggles: /js/xenon-toggles.min.js
  xenonCustom: /js/xenon-custom.min.js
  lozad: /js/lozad.min.js
  html5shiv: /js/html5shiv.min.js
  respond: /js/respond.min.js
  busuanzi: https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js

css:
  hclonely: /css/hclonely.css
  fonts: //fonts.loli.net/css?family=Arimo:400,700,400italic
  linecons: /css/fonts/linecons/css/linecons.min.css
  fontawesome: /css/fonts/fontawesome/css/all.min.css
  bootstrap: /css/bootstrap.min.css
  xenonCore: /css/xenon-core.min.css
  xenonComponents: /css/xenon-components.min.css
  xenonSkins: /css/xenon-skins.min.css
  nav: /css/nav.min.css
