name: hexo-build
on:
  push:
    branches:
      - main
env:
  TZ: Asia/Shanghai
jobs:
  nav-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install Node.js v12.14.0
        uses: actions/setup-node@v2
        with:
          node-version: "12.14.0"
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Setup private rsa key
        env:
          DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
        run: |
          mkdir -p ~/.ssh/
          echo "$DEPLOY_KEY" > ~/.ssh/id_rsa 
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-keyscan gitee.com >> ~/.ssh/known_hosts
      - name: Deploy
        run: |
          git config --global user.name "${{secrets.GIT_NAME}}"
          git config --global user.email "${{secrets.GIT_EMAIL}}"
          npx hexo g -d
      # - name: Deploy
      #   run: |
      #     npm run build
      #     cd public/
      #     git init
      #     git config user.name "${{secrets.GIT_NAME}}"
      #     git config user.email "${{secrets.GIT_EMAIL}}"
      #     git add .
      #     git commit -m "Site updated" -q
      #     git push -f -q "https://${{secrets.GH_TOKEN}}@${{secrets.GH_REF_WEBSTACK}}" master
